title: Melvin Galera
logo: /assets/img/headshot_circular.jpg
description: MS Health Data Science
#show_downloads: true
social_links: true
linkedin: "https://www.linkedin.com/in/melvin-galera-191b1a89"}
theme: jekyll-theme-minimal