title: Melvin Galera
logo: /assets/img/headshot_circular.jpg
description: MS Health Data Science
#show_downloads: true
theme: jekyll-theme-minimal
social_links: true
  - {label: "Linkedin"
    icon: "fab fa-fw fa-linkedin"
    url: "https://www.linkedin.com/in/melvin-galera-191b1a89"}